# Generated by Django 4.1.3 on 2022-11-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True, verbose_name='Date')),
                ('Open', models.FloatField(verbose_name='Open')),
                ('High', models.FloatField(verbose_name='High')),
                ('Low', models.FloatField(verbose_name='Low')),
                ('Close', models.FloatField(verbose_name='Close')),
                ('Adj_Close', models.FloatField(verbose_name='Adj_Close')),
                ('Volume', models.FloatField(verbose_name='Volume')),
            ],
        ),
    ]
