# Generated by Django 4.1.3 on 2022-11-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdata', '0004_alter_csv_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='csv_file',
            field=models.TextField(unique=True),
        ),
    ]
