# Generated by Django 4.1.3 on 2022-11-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdata', '0006_alter_csv_csv_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
