# Generated by Django 4.1.3 on 2022-11-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdata', '0007_delete_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(blank=True)),
                ('Open', models.CharField(blank=True, max_length=100)),
                ('Close', models.CharField(blank=True, max_length=100)),
                ('High', models.CharField(blank=True, max_length=100)),
                ('Low', models.CharField(blank=True, max_length=100)),
                ('Adj_close', models.CharField(blank=True, max_length=100)),
                ('Volume', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
