# Generated by Django 4.1.3 on 2022-11-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdata', '0008_tradeingdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TradeingData',
            new_name='TradingData',
        ),
    ]
