# Generated by Django 4.1.3 on 2022-11-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdata', '0009_rename_tradeingdata_tradingdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingdata',
            old_name='Adj_close',
            new_name='Adj_Close',
        ),
    ]
