# Generated by Django 4.1.3 on 2022-11-08 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rdata', '0010_rename_adj_close_tradingdata_adj_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingdata',
            name='Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
